# Generated by Django 6.0.5 on 2026-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(help_text='UUID4 único de la transacción', max_length=36, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(help_text='Timestamp ISO8601 de la transacción', max_length=26)),
                ('user_id', models.IntegerField(help_text='ID del usuario (1-50000)')),
                ('merchant_id', models.IntegerField(help_text='ID del merchant (1-10000)')),
                ('amount', models.FloatField(help_text='Monto de la transacción (0.01-5000.00)')),
                ('category', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='idx_user_timestamp'), models.Index(fields=['country_code', 'user_id'], name='idx_country_user')],
            },
        ),
    ]
